#!/bin/zsh

BACKLIGHT_LOCATION=/sys/class/backlight/intel_backlight

MAX_BRIGHTNESS=$(cat $BACKLIGHT_LOCATION/max_brightness)
STEP=$((MAX_BRIGHTNESS / 100))
PERCENT=$(seq 0 10 100 | dmenu)

echo $(($PERCENT * $STEP)) > $BACKLIGHT_LOCATION/brightness
