#!/bin/bash
# MAN: Control backlight percentage.
# ARG: None: Use dmenu to set the backlight percentage.
# ARG: $1: up/down $2: percentage.

BACKLIGHT_LOCATION=/sys/class/backlight/intel_backlight

MAX_BRIGHTNESS=$(cat $BACKLIGHT_LOCATION/max_brightness)
BRIGHTNESS=$(cat $BACKLIGHT_LOCATION/brightness)
STEP=$((MAX_BRIGHTNESS / 100))

if [ -z "$1" ]
then
	PERCENT=$(seq 0 10 100 | dmenu)

	echo $(($PERCENT * $STEP)) > $BACKLIGHT_LOCATION/brightness
else
	if [[ "$1" == "up" ]]
	then
		echo $(($BRIGHTNESS + $STEP * $2)) > $BACKLIGHT_LOCATION/brightness
	elif [[ "$1" == "down" ]]
	then
		echo $(($BRIGHTNESS - $STEP * $2)) > $BACKLIGHT_LOCATION/brightness
	else
		echo $(($STEP * $1)) > $BACKLIGHT_LOCATION/brightness
	fi
fi

