#!/bin/zsh

ONP_FOLDER="$HOME/Documents/cda/lessthanthree2"
cd $ONP_FOLDER

ITEM="$(echo "$(ls -d */)\nUnsafe\nAll" | tr -d "/" | dmenu -fn "Roboto Mono for Powerline-11" -p "Select folder:")"

onp $ITEM
