#!/bin/sh
# MAN:
# ARG:

# Colours
NG="\033[0m"
BLUE="\033[0;34m"
RED="\033[0;31m"

DIR=$(dirname $0)

for FILE in $(ls $DIR);
do
	# Print filename
	echo "${BLUE}$(echo $FILE)${NG}"

	# Print man
	echo "${RED}Manual:${NG}\n$(cat "$DIR/$FILE" | grep "^# MAN:" | cut -c "1-7" --complement)"

	# Print arguments
	printf "${RED}Arguments:${NG}\n$(cat "$DIR/$FILE" | grep "^# ARG:" | cut -c "1-7" --complement)${NG}"

	echo "\n"
done
