#!/bin/sh
# MAN:
# ARG:

nohup i3-sensible-terminal >/dev/null 2>&1 &
nohup i3-sensible-terminal >/dev/null 2>&1 &
nohup i3-sensible-terminal >/dev/null 2>&1 &
nohup i3-sensible-terminal >/dev/null 2>&1 &
nohup i3-sensible-terminal >/dev/null 2>&1 &
nohup firefox "https://app.timelyapp.com/695465/calendar/day" "https://app.clubhouse.io" "http://localhost:9000/#/containers" "https://bitbucket.org/dashboard/overview" >/dev/null 2>&1 &
nohup slack >/dev/null 2>&1 &
