#!/bin/bash
# MAN:
# ARG:

I3_LOCATION=~/Code/dotfiles/.i3

echo "Options: (B)uild-in, (H)ome, (P)eakfijn"

read -p "Choice: " INPUT

INPUT=$(echo $INPUT | tr "[:upper:]" "[:lower:]")

case "$INPUT" in
	"build-in" | "b")
		cat $I3_LOCATION/config-base $I3_LOCATION/extends-build-in >  $I3_LOCATION/config
		startx
	;;
	"home" | "h")
		cat $I3_LOCATION/config-base $I3_LOCATION/extends-home >  $I3_LOCATION/config
		startx
	;;
	"peakfijn" | "p")
		cat $I3_LOCATION/config-base $I3_LOCATION/extends-peakfijn >  $I3_LOCATION/config
		startx
	;;
	*)
		echo "No such environtent"
esac

