#!/bin/bash

echo "Options: (B)uild-in, (H)ome, (P)eakfijn"

read -p "Choice: " INPUT

INPUT=$(echo $INPUT | tr "[:upper:]" "[:lower:]")

case "$INPUT" in
	"build-in" | "b")
		ln -sf ~/Code/dotfiles/.i3/config-build-in ~/Code/dotfiles/.i3/config
		startx
	;;
	"home" | "h")
		ln -sf ~/Code/dotfiles/.i3/config-home ~/Code/dotfiles/.i3/config
		startx
	;;
	"peakfijn" | "p")
		ln -sf ~/Code/dotfiles/.i3/config-peakfijn ~/Code/dotfiles/.i3/config
		startx
	;;
	*)
		echo "No such environtent"
esac

