#!/bin/bash

echo "Options: (B)uild-in, (H)ome, (P)eakfijn"

read -p "Choice: " INPUT

INPUT=$(echo $INPUT | tr "[:upper:]" "[:lower:]")

case "$INPUT" in
	"build-in" | "b")
		cp -f ~/Code/dotfiles/.i3/config-build-in ~/Code/dotfiles/.i3/config
		startx
		xrandr --output eDP1 --auto --primary
	;;
	"home" | "h")
		cp -f ~/Code/dotfiles/.i3/config-home ~/Code/dotfiles/.i3/config
		startx
		xrandr --output eDP1 --off --output HDMI1 --auto --primary --output eDP1 --auto
	;;
	"peakfijn" | "p")
		cp -f ~/Code/dotfiles/.i3/config-peakfijn ~/Code/dotfiles/.i3/config
		startx
		# xrandr --output eDP1 --auto --output --auto --primary
	;;
	*)
		echo "No such environtent"
esac

