#!/bin/zsh

case "$1"
in
	"build-in")
		xrandr --output eDP-1 --auto --primary
	;;
	"home")
		xrandr --output eDP-1 --off --output HDMI1 --auto --primary --output DP1 --auto --left-of HDMI1
	;;
	"peakfijn")
		xrandr --output eDP-1 --auto --output HDMI1 --auto --primary --above eDP-1
	;;
esac
