#!/bin/zsh

case "$1"
in
	"build-in")
		xrandr --output eDP-1 --auto --primary
	;;
	"home")
		xrandr --output eDP-1 --off --output DP-1 --auto --primary --output DP-2 --auto --left-of DP-1
	;;
	"peakfijn")
		xrandr --output eDP-1 --auto --output DP-1 --auto --primary --above eDP-1
	;;
esac
