#!/bin/zsh

OPTIONS=$(ls /dev/video* | ag "video[02468]" | tr '[:space:]' '\012')

WEBCAM=$(echo "$OPTIONS" | dmenu -fn "Roboto Mono for Powerline-11" -p "Select display")

$(mpv --demuxer-lavf-format video4linux2 --demuxer-lavf-o-set input_format=mjpeg "$WEBCAM" &nohup)
