#!/bin/zsh

echo "Options: (B)uild-in, (H)ome, (P)eakfijn"

read -p "Choice: " INPUT

INPUT=$(echo $INPUT | tr "[:upper:]" "[:lower:]")

case "$INPUT" in
	"build-in" | "b")
		cp -f ~/Code/dotfiles/.i3/config-build-in ~/Code/dotfiles/.i3/config
		startx "$HOME/Code/dotfiles/.xinitrc-build-in"
	;;
	"home" | "h")
		cp -f ~/Code/dotfiles/.i3/config-home ~/Code/dotfiles/.i3/config
		startx "$HOME/Code/dotfiles/.xinitrc-home"
	;;
	"peakfijn" | "p")
		cp -f ~/Code/dotfiles/.i3/config-peakfijn ~/Code/dotfiles/.i3/config
		startx "$HOME/Code/dotfiles/.xinitrc-peakfijn"
	;;
	*)
		echo "No such environtent"
esac

