#!/bin/bash

echo "Options: (B)uild-in, (H)ome, (P)eakfijn"

read -p "Choice: " INPUT

INPUT=$(echo $INPUT | tr "[:upper:]" "[:lower:]")

case "$INPUT" in
    "build-in" | "b")
        cp -f ~/Code/dotfiles/.xinitrc-build-in ~/Code/dotfiles/.xinitrc
        cp -f ~/Code/dotfiles/.i3/config-build-in ~/Code/dotfiles/.i3/config
        echo "Env: Build-in"
    ;;
    "home" | "h")
        cp -f ~/Code/dotfiles/.xinitrc-home ~/Code/dotfiles/.xinitrc
        cp -f ~/Code/dotfiles/.i3/config-home ~/Code/dotfiles/.i3/config
        echo "Env: Home"
    ;;
    "peakfijn" | "p")
        cp -f ~/Code/dotfiles/.xinitrc-peakfijn ~/Code/dotfiles/.xinitrc
        cp -f ~/Code/dotfiles/.i3/config-peakfijn ~/Code/dotfiles/.i3/config
        echo "env: Peakfijn"
    ;;
    *)
        echo "No such environtent"
esac

startx
