#!/bin/bash

SELECTED=$(echo -e "Build-in\nHome\nPeakfijn" | dmenu -fn "Roboto Mono for Powerline-11" -p "Select display")

case "$SELECTED" in
	"Build-in")
		cp -f ~/Code/dotfiles/.xinitrc-build-in ~/Code/dotfiles/.xinitrc
		cp -f ~/Code/dotfiles/.i3/config-build-in ~/Code/dotfiles/.i3/config
	;;
	"Home")
		cp -f ~/Code/dotfiles/.xinitrc-home ~/Code/dotfiles/.xinitrc
		cp -f ~/Code/dotfiles/.i3/config-home ~/Code/dotfiles/.i3/config
	;;
	"Peakfijn")
		cp -f ~/Code/dotfiles/.xinitrc-peakfijn ~/Code/dotfiles/.xinitrc
		cp -f ~/Code/dotfiles/.i3/config-peakfijn ~/Code/dotfiles/.i3/config
	;;
esac
