#!/bin/sh

# Get the audio outputs
SINK_DESCRIPTIONS=$(pactl list sinks | ag Description | cut --complement -c 1-13)
# Get all the programs that revieve the audio from the outputs
SINK_INPUTS=$(pactl list sink-inputs | ag "Sink Input #")

# Get the names from the outputs to display to the user and have the user pick an output
SINK_DESCRIPTION=$(printf "$SINK_DESCRIPTIONS" | dmenu -i -fn "Roboto Mono for Powerline-11" -p "Select output:")

# Get the index for the answer that the user wrote
DESCRIPTION_INDEX=$(printf "$SINK_DESCRIPTIONS" | ag --number "$SINK_DESCRIPTION" | sed 's/:.*//')
DESCRIPTION_INDEX=$(($DESCRIPTION_INDEX - 1)) # Correct the index hihi

# Set the default output
pactl set-default-sink $DESCRIPTION_INDEX

# Change all the ouputs for the programs that are using the default output
printf "$SINK_INPUTS\n" | while read -r SINK_INPUT
do
	# Get the index for the program
	SINK_INPUT_INDEX=$(printf "$SINK_INPUT" | ag -o "(?!Sink Input#)[0-9]+")
	pactl move-sink-input $SINK_INPUT_INDEX $DESCRIPTION_INDEX
done
