#!/bin/bash

# File extention
EXT=md
# Location where the notes will be stored
NOTES_DIR=$HOME/Notes

# Create notes dir if it doesn't exits
if [ ! -d $NOTES_DIR ]; then
	mkdir $NOTES_DIR
fi

# Date
DATE=$(date '+%d-%m-%Y-%H:%M:%S')

# User input
NAME=$1

# Ask for file name if none was specified
if [ -z "$NAME" ]; then
	printf Name:\ 
	read NAME

	if [ -z "$NAME" ]; then
		NAME=$DATE
	fi
fi

# Give the files the extention
NAME=$NAME.$EXT

# Open the file for editing
vim $NOTES_DIR/$NAME
