#!/bin/bash

# Constants
EXT=md
NOTES_DIR=$HOME/Notes
DATE=$(date '+%d-%m-%Y\_%H:%M:%S')
NOTE_TEMPLATE="Prio (sometime, low, mid, high):\nDate: $DATE\nMessage: "


# Create notes dir if it doesn't exits
if [ ! -d $NOTES_DIR ]; then
	mkdir $NOTES_DIR
fi


# User input
NAME=$1


# Ask for file name if none was specified
if [ -z "$NAME" ]; then
	read -p "Name: " NAME
	
	# If no name is specified date the name to the date
	if [ -z "$NAME" ]; then
		NAME=$DATE
	fi
fi


# Give the files the extention
NAME=$NAME.$EXT


# Create file
touch $NOTES_DIR/$NAME


# Insert note template
echo -e $NOTE_TEMPLATE > $NOTES_DIR/$NAME


# Open file for editing
vim $NOTES_DIR/$NAME
