#!/bin/zsh

# Pathogen install
mkdir -p ~/.vim/autoload ~/.vim/bundle && \
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

# typescript-vim install
git clone https://github.com/leafgarland/typescript-vim.git ~/.vim/bundle/typescript-vim

# vim-js-pretty-template install
git clone https://github.com/Quramy/vim-js-pretty-template.git ~/.vim/bundle/vim-js-pretty-template

# vim-commentray install
git clone git://github.com/tpope/vim-commentary.git ~/.vim/bundle/vim-commentary

# vim-blade install
git clone git://github.com/jwalton512/vim-blade.git ~/.vim/bundle/vim-blade

# scss syntax install
git clone https://github.com/cakebaker/scss-syntax.vim ~/.vim/bundle/scss-syntax

# vim-jsx-pretty install
git clone https://github.com/MaxMEllon/vim-jsx-pretty.git ~/.vim/bundle/vim-jsx-pretty

# ale install
git clone git@github.com:w0rp/ale.git ~/.vim/bundle/ale
# Signify
git clone git@github.com:mhinz/vim-signify.git ~/.vim/bundle/signify

# editorconfig
git clone https://github.com/editorconfig/editorconfig-vim.git ~/.vim/bundle/editorconfig-vim

# vim-javascript
git clone https://github.com/pangloss/vim-javascript.git ~/.vim/bundle/vim-javascript

# airline
git clone https://github.com/vim-airline/vim-airline.git ~/.vim/bundle/vim-airline

# vim-fugitive
git clone https://github.com/tpope/vim-fugitive.git ~/.vim/bundle/vim-fugitive

# fzf-vim
git clone https://github.com/junegunn/fzf.vim.git ~/.vim/bundle/fzf-vim

# NERDTree
git clone https://github.com/scrooloose/nerdtree.git ~/.vim/bundle/nerdtree
