#!/bin/zsh

source ~/.aliases

CHOICE=$(echo -e "Add\nConnect\nRemove" | dmenu -p "Wifi: ")

function add {
	# Get all network names
	NETWORKS=$(nmcli device wifi list | cut -c 9- | tail -n +2 | awk -F "  " '{print $1}' | sort | uniq)

	# Remove separators
	NETWORKS=$(echo "$NETWORKS" | sed -n "/\-\-/!p")

	# Remove white space
	NETWORKS=$(echo "$NETWORKS" | awk '{gsub(/^ +| +$/,"")} {print $0}')

	# Let the user pick a network
	NETWORK=$(echo "$NETWORKS" | dmenu -p "Networks: ")

	nmcli device wifi connect "$NETWORK" --ask
}

function connect {
	NETWORKS=$(nmcli connection show | tail -n +2 | awk -F "  " '{print $1}')

	NETWORK=$(echo "$NETWORKS" | dmenu -p "Networks: ")

	nmcli connection up "$NETWORK"
}

function remove {
	NETWORKS=$(nmcli connection show | tail -n +2 | awk -F "  " '{print $1}')

	NETWORK=$(echo "$NETWORKS" | dmenu -p "Networks: ")

	nmcli connection delete "$NETWORK"
}

case "$CHOICE" in
	"Add")
		add
	;;
	"Connect")
		connect
	;;
	"Remove")
		remove
	;;
esac
